# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: saturday
      time: '05:00'
      # Japan Standard Time (UTC +09:00)
      timezone: 'Asia/Tokyo'
    commit-message:
      prefix: 'Update Github Actions'
      include: scope
    groups:
      security:
        applies-to: security-updates
        patterns: "**"
      development:
        applies-to: version-updates
        patterns: "**"
    directory: '/'
    schedule:
      interval: 'weekly'
      day: saturday
      time: '05:00'
      # Japan Standard Time (UTC +09:00)
      timezone: 'Asia/Tokyo'
    commit-message:
      prefix: Update pnpm dependencies
      prefix-development: Update pnpm dev dependencies
      include: scope
    groups:
      security:
        applies-to: security-updates
        patterns: "**"
      development:
        applies-to: version-updates
        dependency-type: development
      production:
        applies-to: version-updates
        dependency-type: production
